UI/src/electronNav.js, UI/src/js/chat.js, chatbot/lib/chat.js
=> Message history

UI/src/html/chat.html, UI/src/js/chat.js
testing autofill for chat modal
=> Adds an autofill for Join Chat modal

UI/src/electronNav.js, UI/src/html/chat.html
=> On enter submits

UI/src/html/chat.html, UI/src/style.css, chatbot/lib/API.js, chatbot/lib/chat.js
=> Chat styles clean

.gitignore, UI/src/js/charts.js, UI/src/js/commands.js, UI/src/js/users.js, chatbot/lib/chat.js, chatbot/lib/moderator.js, chatbot/lib/users.js
Trying to merge badword list and point leaderboard into dev *without* removing all the new chat page changes.
=> Small improvements, working on bad word list

UI/src/electronNav.js, UI/src/html/chat.html
BTW I only have 7 seconds of recording on Gyazo, so I'm doing things as fast as I can to demonstrate, I'm just fast as fuck boiii
https://i.gyazo.com/c073dccda388a88bcffc5d37d6d77b77.mp4
Pretty sure I got every modal, feel free to test them all though!
fixes https://github.com/aMytho/GlimBoi/issues/15
=> Adds function to detect Enter key and submit modals

UI/src/js/users.js, package-lock.json
No more error, yay! Also cleans up probably the longest line of code in the app
Fixes #29
=> Fixes Points cell undefined & Cleans up Edit Search btn

UI/src/html/chat.html, UI/src/html/commands.html, UI/src/html/events.html, UI/src/html/points.html, UI/src/html/users.html, package-lock.json
These changes are visual only and only affect main UI elements, no modals, text or code has been changed
Consideration has been taken for desktop / tablet / mobile sizes
fixes https://github.com/aMytho/GlimBoi/issues/35
=> Fixing Bootstrap layouts

UI/src/html/settings.html, UI/src/js/settings.js, chatbot/lib/chat.js
This PR adds an optional health reminder for streamers. It will be sent to chat on a set duration. Also fixes one bug with the chat disconnecting when the chat page is reloaded.
=> Health reminders, disconnect fix

UI/src/html/users.html, UI/src/js/users.js
Fixes https://github.com/aMytho/GlimBoi/issues/38
View all quotes didn't work for me, the element userList was missing, I fixed a few visual bugs after that
=> Fixing view all quotes button not working

UI/src/js/charts.js, UI/src/js/chat.js, UI/src/js/home.js, UI/src/js/html.js, UI/src/js/settings.js, UI/src/js/users.js, chatbot/lib/chat.js, chatbot/lib/chat/chatActions.js, chatbot/lib/chat/chatSettings.js, chatbot/lib/chat/chatStats.js, chatbot/lib/commands.js, chatbot/lib/users.js
User data flow has been redesigned. 
This affected quotes, they have also been changed a small bit.
lib/users.js holds a local copy of the user array, this is updated whenever changes are made. The UI pulls from this array for data.
lib/chat.js has also been reworked. It has been spilt into 3 modules (and the original file still exists). This helps improve navigation and load times.
Most inputs now have filters for data validation.
=> Data flow user chat

UI/src/html/chat.html, UI/src/js/chat.js, UI/src/js/events.js, UI/src/js/home.js, chatbot/lib/API.js, chatbot/lib/chat.js, chatbot/lib/chat/chatActions.js, chatbot/lib/chat/chatChannels.js, chatbot/lib/chat/chatMessages.js, chatbot/lib/chat/chatSettings.js, chatbot/lib/commands.js, chatbot/lib/events.js, chatbot/lib/moderator.js, chatbot/lib/users.js, main.js
B I G PR
Moves as much as I can away from chat.js, tries to load as much as I can dynamically, following in @aMytho's style
=> Splits up more chat functions into modules

UI/src/js/commands.js, chatbot/lib/chat/chatMessages.js, chatbot/lib/commands.js
For old commands that didn't get checked before - this should be a last resort
New Commands:
https://i.gyazo.com/d6cc5959404ff87597d014bee192278d.mp4
New Commands
=> Fixed all routes for infinite loops on message

package.json
=== npm audit security report ===
Low             Prototype Pollution
Package         ini
Dependency of   electron [dev]
Path            electron > @electron/get > global-tunnel-ng > npm-conf >
config-chain > ini
More info       https://npmjs.com/advisories/1589
Low             Prototype Pollution
Package         ini
Dependency of   electron-packager [dev]
Path            electron-packager > @electron/get > global-tunnel-ng >
npm-conf > config-chain > ini
More info       https://npmjs.com/advisories/1589
Low             Prototype Pollution
Package         ini
Dependency of   electron-builder [dev]
Path            electron-builder > update-notifier > is-installed-globally >
global-dirs > ini
More info       https://npmjs.com/advisories/1589
Low             Prototype Pollution
Package …
=> Fixes 6 vulnerabilities

UI/index.html, UI/src/electronNav.js, UI/src/js/charts.js, UI/src/js/chat.js, UI/src/js/commands.js, UI/src/js/events.js, UI/src/js/home.js, UI/src/js/html.js, UI/src/js/settings.js, UI/src/js/users.js, chatbot/lib/API.js, chatbot/lib/auth.js, chatbot/lib/chat.js, chatbot/lib/chat/chatActions.js, chatbot/lib/chat/chatChannels.js, chatbot/lib/chat/chatMessages.js, chatbot/lib/chat/chatSettings.js, chatbot/lib/commands.js, chatbot/lib/events.js, chatbot/lib/moderator.js, chatbot/lib/quotes.js, chatbot/lib/users.js, main.js
Check commits at [here](https://github.com/GlobalGamer2015/GlimBoi/commits/main)
=> White space fixing and other fixes

UI/index.html, UI/src/electronNav.js, UI/src/html/ranks.html, UI/src/js/html.js, UI/src/js/ranks.js, UI/src/js/settings.js, UI/src/js/users.js, chatbot/lib/users/userRank.js
This is the base for user ranks. Every user has the `user` rank. It is currently unused. The UI has been created.
=> User ranks

UI/src/electronNav.js, UI/src/html/commands.html, UI/src/html/ranks.html, UI/src/js/commands.js, UI/src/js/html.js, UI/src/js/ranks.js, UI/src/js/users.js, chatbot/lib/chat.js, chatbot/lib/chat/chatActions.js, chatbot/lib/commands.js, chatbot/lib/users.js, chatbot/lib/users/userRank.js, package.json
Adds user ranks
user, Mod, and Streamer
Streamers can make new ranks.
Various functions of the bot are linked to the rank system.
=> Finish user ranks

UI/src/html/commands.html, UI/src/html/events.html, UI/src/html/settings.html, UI/src/js/events.js, chatbot/lib/API.js, chatbot/lib/auth.js, chatbot/lib/chat.js, chatbot/lib/chat/chatActions.js, chatbot/lib/chat/chatChannels.js, chatbot/lib/chat/chatMessages.js, chatbot/lib/commands.js, chatbot/lib/events.js, chatbot/lib/events/bankHeist.js, chatbot/lib/events/duel.js, chatbot/lib/events/glimRealm.js, chatbot/lib/events/poll.js, chatbot/lib/events/raffle.js, chatbot/lib/quotes.js, chatbot/lib/users.js, package.json
Moves existing events into their own modules. Adds some new games. Also adds point settings from chat.
=> Events rework (bankheist, glimrealm, etc)

UI/src/electronNav.js, chatbot/lib/cache.js
Didn't have time to implement it, we can just implement it as we go.
=> Adds Dumb Cache Storage -- currently unused

src/html/homepage.html, src/index.html
Made the Developer Application clickable
=> Added link
